# constants.py
# This file holds static lists of stock tickers.

NIFTY_50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BPCL.NS", "BHARTIARTL.NS",
    "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS",
    "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LTIM.NS",
    "LT.NS", "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS",
    "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SHREECEM.NS", "SBIN.NS",
    "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS"
]

NIFTY_NEXT_50 = [
    "ACC.NS", "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "ATGL.NS",
    "AMBUJACEM.NS", "AUROPHARMA.NS", "DMART.NS", "BAJAJHLDNG.NS", "BANKBARODA.NS",
    "BERGEPAINT.NS", "BEL.NS", "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS",
    "DLF.NS", "GAIL.NS", "GODREJCP.NS", "HAVELLS.NS", "HDFCAMC.NS",
    "HAL.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IOC.NS", "IGL.NS",
    "INDUSTOWER.NS", "JIOFIN.NS", "JSWENERGY.NS", "JINDALSTEL.NS", "LICI.NS",
    "MRF.NS", "MARICO.NS", "MUTHOOTFIN.NS", "NMDC.NS", "PETRONET.NS",
    "PIDILITIND.NS", "PNB.NS", "PGHH.NS", "SAMVARDHANA.NS", "SRF.NS",
    "SIEMENS.NS", "SAIL.NS", "SHRIRAMFIN.NS", "TVSMOTOR.NS", "TRENT.NS",
    "UPL.NS", "VBL.NS", "VEDL.NS", "YESBANK.NS", "ZOMATO.NS"
]

SENSEX_30 = [
    "ASIANPAINT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BHARTIARTL.NS",
    "HCLTECH.NS", "HDFCBANK.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "INDUSINDBK.NS",
    "INFY.NS", "ITC.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS", "M&M.NS",
    "MARUTI.NS", "NESTLEIND.NS", "NTPC.NS", "POWERGRID.NS", "RELIANCE.NS",
    "SBIN.NS", "SUNPHARMA.NS", "TCS.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS"
]

# Combine all lists and remove duplicates
all_tickers = set(NIFTY_50 + NIFTY_NEXT_50 + SENSEX_30)
tickers_to_test = sorted(list(all_tickers)) # Run on all unique stocks
